[project]
name = "indexed-ideas-tools"
version = "0.1.0"
description = "Tooling for indexed-ideas project"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = ">=3.10"
rich-click = ">=1.7.0"

[tasks]
split-schema = "python split_schema.py"
